### ISSUE TITLE
 System.Exception: The authentication response was rejected because the anti-forgery token was invalid.

### ISSUE THREAD

**Issue by characharm** [byo-software/steam-openid-connect-provider#22]
2023-02-20 04:27:12 System.Exception: An error was encountered while handling the remote login.
2023-02-20 04:27:12  ---> System.Exception: The authentication response was rejected because the anti-forgery token was invalid.
2023-02-20 04:27:12    --- End of inner exception stack trace ---
2023-02-20 04:27:12    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
2023-02-20 04:27:12    at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
2023-02-20 04:27:12    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-02-20 04:27:12    at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
2023-02-20 04:27:12    at SteamOpenIdConnectProvider.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /src/Startup.cs:line 110
2023-02-20 04:27:12 --- End of stack trace from previous location ---
2023-02-20 04:27:12    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2023-02-20 04:27:12 [22:27:12 ERR] Connection id "0HMOIP1A02N1Q", Request id "0HMOIP1A02N1Q:00000005": An unhandled exception was thrown by the application.
2023-02-20 04:27:12 System.Exception: An error was encountered while handling the remote login.
2023-02-20 04:27:12  ---> System.Exception: The authentication response was rejected because the anti-forgery token was invalid.
2023-02-20 04:27:12    --- End of inner exception stack trace ---
2023-02-20 04:27:12    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
2023-02-20 04:27:12    at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
2023-02-20 04:27:12    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2023-02-20 04:27:12    at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
2023-02-20 04:27:12    at SteamOpenIdConnectProvider.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /src/Startup.cs:line 110
2023-02-20 04:27:12 --- End of stack trace from previous location ---
2023-02-20 04:27:12    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
2023-02-20 04:27:12    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by characharm** [comment]
[The authentication response was rejected because the anti-forgery token was invalid.](https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/issues/95)

**Comment by Trojaner** [comment]
If I remember correctly this happens when the site is not opened via HTTPS

**Comment by characharm** [comment]
> If I remember correctly this happens when the site is not opened via HTTPS

even in localhost?

**Comment by Trojaner** [comment]
yes

**Comment by characharm** [comment]
Is something with my configuration? Should these fields be in the request? 

namePerson&openid.ax.type.first=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ax.type.last=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ax.type.email2=http%3A%2F%2Fschema.openid.net%2Fcontact%2Femail&openid.ax.type.name2=http%3A%2F%2Fschema.openid.net%2FnamePerson&openid.ax.type.first2=http%3A%2F%2Fschema.openid.net%2FnamePerson%2Ffirst&openid.ax.type.last2=http%3A%2F%2Fschema.openid.net%2FnamePerson%2Flast&openid.ax.required=email,name,first,last,email2,name2,first2,last2

**Comment by STRATZ-Ken** [comment]
Any update on this? Still getting about 90 users a day getting this error.  I checked the defaults of .Net 6.0+ and those settings already seem to be the default.

**Comment by Trojaner** [comment]
This should be fixed with https://github.com/byo-software/steam-openid-connect-provider/commit/1c4a6111e4674d7645c076f913f0b4bbc761bd9c 
If the issue persists please let me know.
