### ISSUE TITLE
System.Exception: The authentication response was rejected because the state parameter was invalid

### ISSUE THREAD

**Issue by stephenwilliams** [byo-software/steam-openid-connect-provider#24]
Would love some help looking into this. Trying to setup the proxy on fly.io and using it with Auth0.com. 

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: The authentication response was rejected because the state parameter was invalid.
 --- End of inner exception stack trace ---
 at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
 at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
 at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
 at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
 at SteamOpenIdConnectProvider.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /src/Startup.cs:line 110
 --- End of stack trace from previous location ---
 at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
 [17:15:26 ERR] Connection id "0HN2F99LUQ2UU", Request id "0HN2F99LUQ2UU:00000002": An unhandled exception was thrown by the application.
 System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: The authentication response was rejected because the state parameter was invalid.
 --- End of inner exception stack trace ---
 at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
 at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync()
 at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
 at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
 at SteamOpenIdConnectProvider.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /src/Startup.cs:line 110
 --- End of stack trace from previous location ---
 at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by Trojaner** [comment]
This happens @ https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/blob/dev/src/AspNet.Security.OpenId/OpenIdAuthenticationHandler.cs#L60

This indicates the "state" query parameter is not forwarded correctly
